# WEB SCRAPING USING BeautifulSoup

In [ ]:
import requests
from bs4 import BeautifulSoup
response=requests.get("https://subslikescript.com/movie/Titanic-120338")
response=response.text
soup=BeautifulSoup(response,"html.parser")
print(soup.prettify())

In [ ]:
print(soup.find("h1").text.strip())

In [ ]:
script=soup.find("div",class_="full-script").text.strip()
print(script)
with open("titanic.txt","w",encoding="utf-8") as file:
    file.write(script)

In [ ]:
import requests
from bs4 import BeautifulSoup
response=requests.get("https://subslikescript.com/")
response=response.text
soup=BeautifulSoup(response,"html.parser")
print(soup.prettify())

In [ ]:
movie=[]
link=[]
a=soup.find("ul",class_="scripts-list")
l=a.find_all("a",href=True)
for i in l:
    movie.append(i.text.strip())
    link.append("https://subslikescript.com"+i["href"])
import pandas as pd
df=pd.DataFrame({"movie":movie,"link":link})
df

In [5]:
url="https://indianexpress.com/latest-news/?ref=latestnews_hp"
import requests
from bs4 import BeautifulSoup
response=requests.get(url)
response=response.text
soup=BeautifulSoup(response,"html.parser")
#print(soup.prettify())
a=soup.find("div",class_="nation")
#print(a)
news=a.find_all("div",class_="title")
#print(news)
for i in news:
    print(i.text.strip())
    print()

Petrol, diesel prices hiked by 90 paise per litre, 2nd increase in under a week as OMCs continue to bleed

CBSE Class 12th 2026 result re-evaluation starts today, how to apply, fees, direct link

At least 120 dead in Ebola outbreak in DR Congo, official says

Stray Dog Case Live Updates: Supreme Court to deliver judgment shortly

Russia attacks Ukraine’s Danube port city, Ukraine launches drones towards Moscow

US extends sanctions waiver for Russian crude again: The move, its impact on India explained

NEET-UG 2026 paper leak: CBI questions NTA office staff, records statements

Techie appeals against Rs 40 lakh alimony payout, Jharkhand High Court raises it to Rs 70 lakh: Here’s why

‘Violence in the name of protest unacceptable’: Delhi HC on 2022 stir outside J P Nadda’s home

‘AI is no longer a feature but an operating model for enterprises’: Michael Dell at Las Vegas conference

Procedure not followed in demolition of AIMIM corporator’s house: HC

Saif Ali Khan on why he shut down his successful production banner: ‘It’s a massive pain’

Supreme Court to announce ruling on feeding stray dogs: Recalling the case

Haryana lodges FIRs against 22 employees for skipping census duty

KCET 2026: CBSE, ISC, other board exam students asked to update Class 12 marks for UGCET merit list

Rupee slips 18 paise to 96.38 against US dollar; stock markets open slightly higher

Yogendra Yadav writes: State push for Indian knowledge systems is a farce. But dismissing them is a mistake

Chef Sanjeev Kapoor says poha causes major blood sugar spikes: ‘If rice is bad, it is worse’

Debuts in both Hindi, Tamil flopped, but Jyotika was embraced by South while Bollywood rejected her

NEET-UG paper leak: At Pune shopping complex, a shut dental clinic and a ‘beauty parlour’ that isn’t

Salman Khan’s mother was concerned after his last post about loneliness: ‘How can I be alone?’

Asia is ageing. Can primary care keep up?

Google, Blackstone to launch AI cloud venture to meet data centre demand

‘I could not call myself an engineer’: How Maharashtra’s aborted Muslim quota left a Beed man without his degree for nine years

Bail under UAPA: How different Supreme Court benches have delivered different rulings in the past

In [1]:
# write a python program using Beautifulsoup library create dataframe of
#statement, link, source, date 
#from "https://www.politifact.com/"
import requests
from bs4 import BeautifulSoup
response=requests.get("https://www.politifact.com/")
response=response.text
soup=BeautifulSoup(response,"html.parser")

In [12]:
source=[]
statement=[]
date=[]
link=[]
a=soup.find("div",class_="embla")
#print(a)
b=a.find_all("div",class_="embla__slide caro-listing__item")
#print(b)
for i in b:
    s=i.find("div",class_="m-statement__meta").find("a").text.strip()
    source.append(s)
    statement.append(i.find("div",class_="m-statement__quote").find("a").text.strip())
    link.append("https://www.politifact.com"+i.find("div",class_="m-statement__quote").
        find("a")["href"])
    d=i.find("div",class_="m-statement__desc").text.strip()
    l=d.split()
    date.append((" ".join(l[2:5])))
import pandas as pd
df=pd.DataFrame({"source":source,"statement":statement,"link":link,"date":date})
print(df)

                   source                                          statement  \
0                 X posts  Video shows U.S. Rep. Byron Donalds saying, “I...
1                 X posts  An American passenger on the cruise ship invol...
2            Marcy Kaptur  Republicans “want you to pay $1 Billion for a ...
3                 X posts  “California only has ‘enough’ oil and gas supp...
4  Restoration of America  “83% of us favor requiring a photo ID to vote....
5            Social Media  Video shows a US soldier crying and saying she...

                                                link            date
0  https://www.politifact.com/factchecks/2026/may...    May 14, 2026
1  https://www.politifact.com/factchecks/2026/may...     May 6, 2026
2  https://www.politifact.com/factchecks/2026/may...     May 5, 2026
3  https://www.politifact.com/factchecks/2026/may...     May 6, 2026
4  https://www.politifact.com/factchecks/2026/apr...  April 13, 2026
5  https://www.politifact.com/factchecks/2026/apr...   April 4, 2026

# offline webscraping

In [ ]:
# write a python program to scrap data from "30 Most Popular Movies Right Now_ What to Watch In Theaters and Streaming __ 
#Rotten Tomatoes – Movie and TV News" and create dataframe with columns movie 
#name, rating, director

In [22]:
from bs4 import BeautifulSoup
file=open("30 Most Popular Movies Right Now_ What to Watch In Theaters and Streaming __ Rotten Tomatoes – Movie and TV News.html",
          encoding="utf-8")
response=file.read()
soup=BeautifulSoup(response,"html.parser")
movie=[]
rating=[]
director=[]
a=soup.find_all("div",class_="col-sm-18 col-full-xs countdown-item-content")
for i in a:
    movie.append(i.find("h2").find("a").text.strip())
    rating.append(i.find("span",class_="tMeterScore").text.strip())
    director.append(i.find("div",class_="info director").find("a").text.strip())

import pandas as pd
df=pd.DataFrame({"movie":movie,"rating":rating,"director":director})
df

                                      movie rating               director
0          Transformers: Rise of the Beasts    53%       Steven Caple Jr.
1       Spider-Man: Across the Spider-Verse    96%     Joaquim Dos Santos
2                        The Little Mermaid    67%           Rob Marshall
3                             The Boogeyman    63%             Rob Savage
4     Are You There God? It's Me, Margaret.    99%     Kelly Fremon Craig
5                                    Fast X    56%        Louis Leterrier
6                                BlackBerry    98%           Matt Johnson
7                               The Machine    27%          Peter Atencio
8                                   Reality    92%            Tina Satter
9                               Flamin' Hot    68%           Eva Longoria
10           Guardians of the Galaxy Vol. 3    82%             James Gunn
11                                Blue Jean    94%         Georgia Oakley
12                               Past Lives    97%            Celine Song
13              The Super Mario Bros. Movie    58%          Aaron Horvath
14                 Avatar: The Way of Water    76%          James Cameron
15               Guy Ritchie's The Covenant    83%            Guy Ritchie
16                                Bumblebee    91%          Travis Knight
17                                Nefarious    33%           Cary Solomon
18                                     Sisu    93%       Jalmari Helander
19                     You Hurt My Feelings    95%      Nicole Holofcener
20                     John Wick: Chapter 4    94%         Chad Stahelski
21                           Leave No Trace    80%           Irene Taylor
22                          About My Father    36%          Laura Terruso
23  Dungeons & Dragons: Honor Among Thieves    90%  Jonathan M. Goldstein
24                             Transformers    57%            Michael Bay
25                                 My Fault              Domingo González
26                         A Beautiful Life    50%             Mehdi Avaz
27     The Angry Black Girl and Her Monster    88%        Bomani J. Story
28                                  Missing    87%           Will Merrick
29                                      Air    92%            Ben Affleck

In [ ]:
# write a python program to scrap data from "Certified used Mercedes-Benz for sale.html"
#create dataframe with columns carname, review count, rating, price,dealer name, mileage

In [33]:
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
file=open("Certified used Mercedes-Benz for sale.html",
          encoding="utf-8")
response=file.read()
soup=BeautifulSoup(response,"html.parser")
carname=[]
review_count=[] 
rating=[]
price=[]
dealer=[]
name=[]
mileage=[]
a=soup.find_all("div",class_="vehicle-details")
for i in a:
    carname.append(i.find("h2",class_="title").text.strip())
    mileage.append(i.find("div",class_="mileage").text.strip())
    review_count.append(i.find("span",class_="sds-rating__link sds-button-link").
        text.strip().split()[0][1:])
    dealer.append(i.find("div",class_="dealer-name").text.strip())
    price.append(i.find("span",class_="primary-price").text.strip())
    try:
        rating.append(i.find("span",class_="sds-rating__count").text.strip())
    except:
        rating.append(np.nan)
        
df=pd.DataFrame({"car name":carname,"mileage":mileage,"review_count":review_count,
               "dealer":dealer,"price":price,"rating":rating })
df

,car name,mileage,review_count,dealer,price,rating
0,2020 Mercedes-Benz CLA 250 Base 4MATIC,"28,744 mi.",130,Mercedes-Benz of Lynnwood,"$35,995",4.4
1,2019 Mercedes-Benz AMG GT 53 Base,"25,771 mi.",117,International Autos,"$79,995",4.0
2,2021 Mercedes-Benz AMG GLE 53 Base,"22,374 mi.",38,John Sisson Motors,"$80,923",2.8
3,2022 Mercedes-Benz AMG CLA 45 Base 4MATIC,"10,595 mi.",30,Mercedes-Benz of Santa Rosa,"$56,633",NaN
4,2021 Mercedes-Benz AMG GLE 53 Base,"33,622 mi.",152,Mercedes-Benz of Rochester,"$76,995",4.7
5,2021 Mercedes-Benz E-Class E 450 4MATIC,"12,477 mi.","5,283",Benzel-Busch Motor Car,"$76,532",4.5
6,2021 Mercedes-Benz AMG GLE 63 S-Model 4MATIC,"22,383 mi.",174,Mercedes-Benz of Lancaster,"$102,990",4.8
7,2019 Mercedes-Benz S-Class S 560,"49,332 mi.","2,016",Mercedes-Benz of Ontario,"$54,580",4.8
8,2021 Mercedes-Benz AMG GLE 53 Base,"37,688 mi.",38,John Sisson Motors,"$76,715",2.8
9,2021 Mercedes-Benz GLA 250 Base,"19,521 mi.",264,Mercedes-Benz of Augusta,"$34,999",4.6
10,2022 Mercedes-Benz AMG C 43 Base 4MATIC,"14,420 mi.","1,327",Mercedes-Benz of Chicago,"$62,991",4.8
11,2018 Mercedes-Benz AMG C 43 Base 4MATIC,"34,555 mi.","1,388",Mercedes-Benz of South Orlando,"$39,999",4.4
12,2021 Mercedes-Benz E-Class E 450 4MATIC,"16,474 mi.",226,Contemporary Motor Cars Inc.,"$74,998",4.8
13,2021 Mercedes-Benz S-Class S 580 4MATIC,"10,233 mi.","2,788",Mercedes-Benz of Fort Washington,"$99,822",4.5
14,2022 Mercedes-Benz GLE 450 AWD 4MATIC,"6,800 mi.","1,327",Mercedes-Benz of Chicago,"$73,990",4.8
15,2018 Mercedes-Benz GLC 300 Base 4MATIC,"54,467 mi.","2,788",Mercedes-Benz of Fort Washington,"$29,151",4.5
16,2022 Mercedes-Benz AMG GLA 35 Base,"8,690 mi.","2,788",Mercedes-Benz of Fort Washington,"$49,736",4.5
17,2022 Mercedes-Benz GLB 250 Base,"8,158 mi.","3,521",Mercedes-Benz Of Tampa,"$42,000",4.1
18,2022 Mercedes-Benz S-Class S 500 4MATIC,"8,401 mi.","1,016",Mercedes-Benz of Walnut Creek,"$86,986",4.5
19,2020 Mercedes-Benz AMG S 63 Base 4MATIC,"24,958 mi.","1,000",Autobahn Motors,"$105,997",4.8
20,2021 Mercedes-Benz GLC 300 Base 4MATIC,"49,278 mi.",292,Bergstrom Luxury on Victory Lane,"$37,280",4.2

In [41]:
from bs4 import BeautifulSoup
file=open("SENSEX Top Gainers, BSE Daily Top Gainers - Stock Market.html",
          encoding="utf-8")
response=file.read()
soup=BeautifulSoup(response,"html.parser")
a=soup.find("table")
b=a.find_all("tr")
#print(b)
company=[]
current_price=[]
prev_close=[]
date=[]
change=[]
ch_per=[]
high=[]
low=[]
for i in b[1:]:
    company.append(i.find("td",class_="v-align").text.strip())
    current_price.append(i.find("td",class_="txt-right v-align").text.strip())
    prev_close.append(i.find("td",class_="txt-right no-wrap").text.strip().split("\n")[0])
    date.append(i.find("td",class_="txt-right no-wrap").text.strip().split("\n")[1])
    c=i.find_all("td",class_="txt-ctr")
    #print(c)
    for j in c[0]:
        d=j.text.strip()
        change.append(d)
    for k in c[1]:
        d=k.text.strip()
        ch_per.append(d)
    high.append(i.find("div",class_="btm clearfix").text.strip().split("\n")[0])
    low.append(i.find("div",class_="btm clearfix").text.strip().split("\n")[1])
# create dataframe

['584.00',
 '1170.00',
 '3232.00',
 '249.75',
 '1304.40',
 '284.35',
 '2390.30',
 '7375.00',
 '1610.95',
 '4670.80',
 '2663.25',
 '157.80',
 '3326.45',
 '115.25']

In [44]:
import pandas as pd
from io import StringIO
df=pd.read_html(StringIO(response))
print(df[0])

              Company  Current Price      Prev Close Date  Change Change %  \
0         Tata Motors         583.30   569.55  16-06-2023   13.75    2.41%
1           HCL Tech.        1168.20  1149.00  16-06-2023   19.20    1.67%
2                 TCS        3227.20  3175.25  16-06-2023   51.95    1.64%
3   Power Grid Corpn.         248.95   246.10  16-06-2023    2.85    1.16%
4             Infosys        1303.15  1292.65  16-06-2023   10.50    0.81%
5             Vedanta         282.60   280.35  16-06-2023    2.25    0.80%
6     Larsen & Toubro        2382.20  2366.50  16-06-2023   15.70    0.66%
7       Bajaj Finance        7247.85  7203.40  16-06-2023   44.45    0.62%
8           HDFC Bank        1608.30  1602.10  16-06-2023    6.20    0.39%
9          Bajaj Auto        4659.90  4642.75  16-06-2023   17.15    0.37%
10               HDFC        2657.85  2651.15  16-06-2023    6.70    0.25%
11               ONGC         157.25   156.90  16-06-2023    0.35    0.22%
12       Asian Paints        3318.40  3315.20  16-06-2023    3.20    0.10%
13         Tata Steel         114.30   114.25  16-06-2023    0.05    0.04%

      Day's Low/High
0     562.40  584.00
1   1130.15  1170.00
2   3201.60  3232.00
3     243.25  249.75
4   1291.00  1304.40
5     278.70  284.35
6   2355.00  2390.30
7   7202.00  7375.00
8   1590.90  1610.95
9   4570.70  4670.80
10  2632.00  2663.25
11    156.60  157.80
12  3276.30  3326.45
13    113.50  115.25

# rest API( representational state transfer application programming interface)

In [1]:
import requests,json
city=input("enter city: ")
api_key="81c148fded66cf6945b9fe227e878f6e"
url="http://api.openweathermap.org/geo/1.0/direct?q="+city+"&appid="+api_key
response=requests.get(url)
detail=response.json()
print(detail)
lat=detail[0]["lat"]
print(lat)
long=detail[0]["lon"]
print(long)

enter city:  pune

[{'name': 'Pune', 'local_names': {'sr': 'Пуне', 'bg': 'Пуна', 'mr': 'पुणे शहर', 'ps': 'پونی', 'he': 'פונה', 'az': 'Puna', 'ru': 'Пуне', 'ne': 'पुणे', 'be': 'Пуна', 'zh': '浦那', 'hu': 'Púne', 'te': 'పూణే', 'hr': 'Pune', 'fa': 'پونه', 'pa': 'ਪੁਣੇ', 'de': 'Pune', 'hi': 'पुणे', 'uk': 'Пуне', 'ml': 'പൂണെ', 'kn': 'ಪುಣೆ', 'ur': 'شہر پونے', 'ar': 'مدينة بونه', 'bn': 'পুনে', 'en': 'Pune', 'fr': 'Pune', 'el': 'Πούνε', 'sl': 'Pune'}, 'lat': 18.5213738, 'lon': 73.8545071, 'country': 'IN', 'state': 'Maharashtra'}]
18.5213738
73.8545071

# get current weather API

In [6]:
url="https://api.openweathermap.org/data/2.5/weather?lat="+str(lat)+"&lon="+str(long)+"&appid="+api_key+"&units=metric"
response=requests.get(url)
result=response.json()
print(json.dumps(result,indent=4))

{
    "coord": {
        "lon": 73.8545,
        "lat": 18.5214
    },
    "weather": [
        {
            "id": 804,
            "main": "Clouds",
            "description": "overcast clouds",
            "icon": "04d"
        }
    ],
    "base": "stations",
    "main": {
        "temp": 28.56,
        "feels_like": 29.11,
        "temp_min": 28.56,
        "temp_max": 28.56,
        "pressure": 1012,
        "humidity": 50,
        "sea_level": 1012,
        "grnd_level": 940
    },
    "visibility": 10000,
    "wind": {
        "speed": 2.26,
        "deg": 267,
        "gust": 2.61
    },
    "clouds": {
        "all": 100
    },
    "dt": 1779765650,
    "sys": {
        "type": 2,
        "id": 2104163,
        "country": "IN",
        "sunrise": 1779755297,
        "sunset": 1779802513
    },
    "timezone": 19800,
    "id": 1259229,
    "name": "Pune",
    "cod": 200
}

In [7]:
print("temperature:",result["main"]["temp"])

temperature: 28.56

In [8]:
print("wind speed:",result["wind"]["speed"])

wind speed: 2.26

In [14]:
# print aqi of any city
import requests,json
city=input("enter city: ")
api_key="81c148fded66cf6945b9fe227e878f6e"
url="http://api.openweathermap.org/geo/1.0/direct?q="+city+"&appid="+api_key
response=requests.get(url)
detail=response.json()
print(detail)
lat=detail[0]["lat"]
print(lat)
long=detail[0]["lon"]
print(long)
url1="http://api.openweathermap.org/data/2.5/air_pollution?lat="+str(lat)+"&lon="+str(long)+"&appid="+api_key
response=requests.get(url1)
result=response.json()
print(json.dumps(result,indent=4))
print("AQI:",result["list"][0]["main"]["aqi"])

enter city:  pune

[{'name': 'Pune', 'local_names': {'fr': 'Pune', 'zh': '浦那', 'ml': 'പൂണെ', 'ne': 'पुणे', 'pa': 'ਪੁਣੇ', 'el': 'Πούνε', 'ps': 'پونی', 'sl': 'Pune', 'sr': 'Пуне', 'ru': 'Пуне', 'ar': 'مدينة بونه', 'kn': 'ಪುಣೆ', 'be': 'Пуна', 'fa': 'پونه', 'te': 'పూణే', 'hr': 'Pune', 'mr': 'पुणे शहर', 'bn': 'পুনে', 'he': 'פונה', 'en': 'Pune', 'uk': 'Пуне', 'bg': 'Пуна', 'ur': 'شہر پونے', 'hu': 'Púne', 'de': 'Pune', 'az': 'Puna', 'hi': 'पुणे'}, 'lat': 18.5213738, 'lon': 73.8545071, 'country': 'IN', 'state': 'Maharashtra'}]
18.5213738
73.8545071
{
    "coord": {
        "lon": 73.8545,
        "lat": 18.5214
    },
    "list": [
        {
            "main": {
                "aqi": 1
            },
            "components": {
                "co": 88.17,
                "no": 0.35,
                "no2": 1,
                "o3": 27.42,
                "so2": 1.14,
                "pm2_5": 1.88,
                "pm10": 3.93,
                "nh3": 1.69
            },
            "dt": 1779767022
        }
    ]
}
AQI: 1

In [20]:
#5 days 3 hr weather in dataframe
url="http://api.openweathermap.org/data/2.5/forecast?lat="+str(lat)+"&lon="+str(long)+"&appid="+api_key+"&units=metric"

response=requests.get(url)
detail=response.json()
print(json.dumps(detail,indent=4))
date_time=[]
temp=[]
weather=[]

{
    "cod": "200",
    "message": 0,
    "cnt": 40,
    "list": [
        {
            "dt": 1779775200,
            "main": {
                "temp": 29.86,
                "feels_like": 30.01,
                "temp_min": 29.86,
                "temp_max": 31.36,
                "pressure": 1012,
                "sea_level": 1012,
                "grnd_level": 939,
                "humidity": 44,
                "temp_kf": -1.5
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d"
                }
            ],
            "clouds": {
                "all": 100
            },
            "wind": {
                "speed": 4.77,
                "deg": 289,
                "gust": 5.49
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "d"
            },
            "dt_txt": "2026-05-26 06:00:00"
        },
        {
            "dt": 1779786000,
            "main": {
                "temp": 32.48,
                "feels_like": 32.26,
                "temp_min": 32.48,
                "temp_max": 34.16,
                "pressure": 1009,
                "sea_level": 1009,
                "grnd_level": 937,
                "humidity": 36,
                "temp_kf": -1.68
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d"
                }
            ],
            "clouds": {
                "all": 86
            },
            "wind": {
                "speed": 4.54,
                "deg": 300,
                "gust": 3.83
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "d"
            },
            "dt_txt": "2026-05-26 09:00:00"
        },
        {
            "dt": 1779796800,
            "main": {
                "temp": 34.57,
                "feels_like": 34.47,
                "temp_min": 34.57,
                "temp_max": 34.57,
                "pressure": 1007,
                "sea_level": 1007,
                "grnd_level": 936,
                "humidity": 32,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d"
                }
            ],
            "clouds": {
                "all": 54
            },
            "wind": {
                "speed": 4.16,
                "deg": 289,
                "gust": 3.03
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "d"
            },
            "dt_txt": "2026-05-26 12:00:00"
        },
        {
            "dt": 1779807600,
            "main": {
                "temp": 29.69,
                "feels_like": 32.07,
                "temp_min": 29.69,
                "temp_max": 29.69,
                "pressure": 1010,
                "sea_level": 1010,
                "grnd_level": 937,
                "humidity": 59,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01n"
                }
            ],
            "clouds": {
                "all": 4
            },
            "wind": {
                "speed": 5.41,
                "deg": 273,
                "gust": 6.7
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "dt_txt": "2026-05-26 15:00:00"
        },
        {
            "dt": 1779818400,
            "main": {
                "temp": 27.49,
                "feels_like": 29.93,
                "temp_min": 27.49,
                "temp_max": 27.49,
                "pressure": 1010,
                "sea_level": 1010,
                "grnd_level": 938,
                "humidity": 72,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01n"
                }
            ],
            "clouds": {
                "all": 4
            },
            "wind": {
                "speed": 4.4,
                "deg": 268,
                "gust": 6.79
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "dt_txt": "2026-05-26 18:00:00"
        },
        {
            "dt": 1779829200,
            "main": {
                "temp": 25.79,
                "feels_like": 26.44,
                "temp_min": 25.79,
                "temp_max": 25.79,
                "pressure": 1010,
                "sea_level": 1010,
                "grnd_level": 938,
                "humidity": 77,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01n"
                }
            ],
            "clouds": {
                "all": 0
            },
            "wind": {
                "speed": 4.14,
                "deg": 271,
                "gust": 6.63
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "dt_txt": "2026-05-26 21:00:00"
        },
        {
            "dt": 1779840000,
            "main": {
                "temp": 24.8,
                "feels_like": 25.45,
                "temp_min": 24.8,
                "temp_max": 24.8,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 938,
                "humidity": 81,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 801,
                    "main": "Clouds",
                    "description": "few clouds",
                    "icon": "02n"
                }
            ],
            "clouds": {
                "all": 14
            },
            "wind": {
                "speed": 3.7,
                "deg": 259,
                "gust": 6.21
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "dt_txt": "2026-05-27 00:00:00"
        },
        {
            "dt": 1779850800,
            "main": {
                "temp": 27.7,
                "feels_like": 29.22,
                "temp_min": 27.7,
                "temp_max": 27.7,
                "pressure": 1012,
                "sea_level": 1012,
                "grnd_level": 940,
                "humidity": 62,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01d"
                }
            ],
            "clouds": {
                "all": 4
            },
            "wind": {
                "speed": 4.32,
                "deg": 268,
                "gust": 5.83
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "d"
            },
            "dt_txt": "2026-05-27 03:00:00"
        },
        {
            "dt": 1779861600,
            "main": {
                "temp": 33.89,
                "feels_like": 34.3,
                "temp_min": 33.89,
                "temp_max": 33.89,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 939,
                "humidity": 36,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 801,
                    "main": "Clouds",
                    "description": "few clouds",
                    "icon": "02d"
                }
            ],
            "clouds": {
                "all": 20
            },
            "wind": {
                "speed": 5.07,
                "deg": 281,
                "gust": 5.03
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "d"
            },
            "dt_txt": "2026-05-27 06:00:00"
        },
        {
            "dt": 1779872400,
            "main": {
                "temp": 36.47,
                "feels_like": 37.45,
                "temp_min": 36.47,
                "temp_max": 36.47,
                "pressure": 1008,
                "sea_level": 1008,
                "grnd_level": 937,
                "humidity": 32,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 801,
                    "main": "Clouds",
                    "description": "few clouds",
                    "icon": "02d"
                }
            ],
            "clouds": {
                "all": 19
            },
            "wind": {
                "speed": 5.39,
                "deg": 280,
                "gust": 4.45
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "d"
            },
            "dt_txt": "2026-05-27 09:00:00"
        },
        {
            "dt": 1779883200,
            "main": {
                "temp": 33.83,
                "feels_like": 34.9,
                "temp_min": 33.83,
                "temp_max": 33.83,
                "pressure": 1008,
                "sea_level": 1008,
                "grnd_level": 937,
                "humidity": 39,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 801,
                    "main": "Clouds",
                    "description": "few clouds",
                    "icon": "02d"
                }
            ],
            "clouds": {
                "all": 17
            },
            "wind": {
                "speed": 7.85,
                "deg": 290,
                "gust": 6.39
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "d"
            },
            "dt_txt": "2026-05-27 12:00:00"
        },
        {
            "dt": 1779894000,
            "main": {
                "temp": 28.94,
                "feels_like": 30.49,
                "temp_min": 28.94,
                "temp_max": 28.94,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 939,
                "humidity": 57,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01n"
                }
            ],
            "clouds": {
                "all": 0
            },
            "wind": {
                "speed": 5.59,
                "deg": 267,
                "gust": 6.85
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "dt_txt": "2026-05-27 15:00:00"
        },
        {
            "dt": 1779904800,
            "main": {
                "temp": 27.15,
                "feels_like": 28.51,
                "temp_min": 27.15,
                "temp_max": 27.15,
                "pressure": 1012,
                "sea_level": 1012,
                "grnd_level": 939,
                "humidity": 63,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01n"
                }
            ],
            "clouds": {
                "all": 9
            },
            "wind": {
                "speed": 3.78,
                "deg": 261,
                "gust": 5.84
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "dt_txt": "2026-05-27 18:00:00"
        },
        {
            "dt": 1779915600,
            "main": {
                "temp": 25.47,
                "feels_like": 25.98,
                "temp_min": 25.47,
                "temp_max": 25.47,
                "pressure": 1010,
                "sea_level": 1010,
                "grnd_level": 938,
                "humidity": 73,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01n"
                }
            ],
            "clouds": {
                "all": 0
            },
            "wind": {
                "speed": 4.15,
                "deg": 261,
                "gust": 6.87
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "dt_txt": "2026-05-27 21:00:00"
        },
        {
            "dt": 1779926400,
            "main": {
                "temp": 24.47,
                "feels_like": 25.11,
                "temp_min": 24.47,
                "temp_max": 24.47,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 939,
                "humidity": 82,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01n"
                }
            ],
            "clouds": {
                "all": 0
            },
            "wind": {
                "speed": 3.83,
                "deg": 259,
                "gust": 6.74
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "dt_txt": "2026-05-28 00:00:00"
        },
        {
            "dt": 1779937200,
            "main": {
                "temp": 27.53,
                "feels_like": 28.97,
                "temp_min": 27.53,
                "temp_max": 27.53,
                "pressure": 1013,
                "sea_level": 1013,
                "grnd_level": 940,
                "humidity": 62,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01d"
                }
            ],
            "clouds": {
                "all": 0
            },
            "wind": {
                "speed": 4.94,
                "deg": 268,
                "gust": 6.78
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "d"
            },
            "dt_txt": "2026-05-28 03:00:00"
        },
        {
            "dt": 1779948000,
            "main": {
                "temp": 33.72,
                "feels_like": 34.04,
                "temp_min": 33.72,
                "temp_max": 33.72,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 939,
                "humidity": 36,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01d"
                }
            ],
            "clouds": {
                "all": 0
            },
            "wind": {
                "speed": 5.11,
                "deg": 268,
                "gust": 5.4
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "d"
            },
            "dt_txt": "2026-05-28 06:00:00"
        },
        {
            "dt": 1779958800,
            "main": {
                "temp": 36.72,
                "feels_like": 36.76,
                "temp_min": 36.72,
                "temp_max": 36.72,
                "pressure": 1009,
                "sea_level": 1009,
                "grnd_level": 937,
                "humidity": 28,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01d"
                }
            ],
            "clouds": {
                "all": 0
            },
            "wind": {
                "speed": 5.71,
                "deg": 285,
                "gust": 5.27
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "d"
            },
            "dt_txt": "2026-05-28 09:00:00"
        },
        {
            "dt": 1779969600,
            "main": {
                "temp": 34.49,
                "feels_like": 34.78,
                "temp_min": 34.49,
                "temp_max": 34.49,
                "pressure": 1008,
                "sea_level": 1008,
                "grnd_level": 936,
                "humidity": 34,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01d"
                }
            ],
            "clouds": {
                "all": 0
            },
            "wind": {
                "speed": 6.73,
                "deg": 285,
                "gust": 5.88
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "d"
            },
            "dt_txt": "2026-05-28 12:00:00"
        },
        {
            "dt": 1779980400,
            "main": {
                "temp": 29.2,
                "feels_like": 30.19,
                "temp_min": 29.2,
                "temp_max": 29.2,
                "pressure": 1010,
                "sea_level": 1010,
                "grnd_level": 938,
                "humidity": 52,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",
                    "icon": "01n"
                }
            ],
            "clouds": {
                "all": 0
            },
            "wind": {
                "speed": 5.67,
                "deg": 268,
                "gust": 7.04
            },
            "visibility": 10000,
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "dt_txt": "2026-05-28 15:00:00"
        },
        {
            "dt": 1779991200,
            "main": {
                "temp": 26.27,
                "feels_like": 26.27,
                "temp_min": 26.27,
                "temp_max": 26.27,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 939,
                "humidity": 68,
                "temp_kf": 0
            },
            "weather": [
                {
                    "id": 800,
                    "main": "Clear",
                    "description": "clear sky",

In [21]:
for i in detail["list"]:
    date_time.append(i["dt_txt"])
    temp.append(i["main"]["temp"])
    try:
        weather.append(i["weather"][0]["description"])
    except:
        weather.append("nan")
print(len(date_time),len(temp),len(weather))
import pandas as pd
df=pd.DataFrame({"date_time":date_time,"temp":temp,"weather":weather})
df

40 40 40

              date_time   temp          weather
0   2026-05-26 06:00:00  29.86  overcast clouds
1   2026-05-26 09:00:00  32.48  overcast clouds
2   2026-05-26 12:00:00  34.57    broken clouds
3   2026-05-26 15:00:00  29.69        clear sky
4   2026-05-26 18:00:00  27.49        clear sky
5   2026-05-26 21:00:00  25.79        clear sky
6   2026-05-27 00:00:00  24.80       few clouds
7   2026-05-27 03:00:00  27.70        clear sky
8   2026-05-27 06:00:00  33.89       few clouds
9   2026-05-27 09:00:00  36.47       few clouds
10  2026-05-27 12:00:00  33.83       few clouds
11  2026-05-27 15:00:00  28.94        clear sky
12  2026-05-27 18:00:00  27.15        clear sky
13  2026-05-27 21:00:00  25.47        clear sky
14  2026-05-28 00:00:00  24.47        clear sky
15  2026-05-28 03:00:00  27.53        clear sky
16  2026-05-28 06:00:00  33.72        clear sky
17  2026-05-28 09:00:00  36.72        clear sky
18  2026-05-28 12:00:00  34.49        clear sky
19  2026-05-28 15:00:00  29.20        clear sky
20  2026-05-28 18:00:00  26.27        clear sky
21  2026-05-28 21:00:00  24.62        clear sky
22  2026-05-29 00:00:00  24.64        clear sky
23  2026-05-29 03:00:00  27.98        clear sky
24  2026-05-29 06:00:00  33.65        clear sky
25  2026-05-29 09:00:00  36.06        clear sky
26  2026-05-29 12:00:00  33.54        clear sky
27  2026-05-29 15:00:00  28.18        clear sky
28  2026-05-29 18:00:00  25.76        clear sky
29  2026-05-29 21:00:00  24.79        clear sky
30  2026-05-30 00:00:00  24.68        clear sky
31  2026-05-30 03:00:00  28.42        clear sky
32  2026-05-30 06:00:00  33.36        clear sky
33  2026-05-30 09:00:00  35.60        clear sky
34  2026-05-30 12:00:00  32.80        clear sky
35  2026-05-30 15:00:00  27.22        clear sky
36  2026-05-30 18:00:00  26.41        clear sky
37  2026-05-30 21:00:00  25.78        clear sky
38  2026-05-31 00:00:00  25.56        clear sky
39  2026-05-31 03:00:00  28.82        clear sky

In [22]:
import requests
import json
import pandas as pd
# Basic GET request
url = "https://jsonplaceholder.typicode.com/posts/1"
response = requests.get(url)
print(response)

<Response [200]>

In [23]:
print(response.status_code)
# View raw response text
print(response.text)
# Convert response to JSON
data = response.json()
print(data)
print(type(data))

200
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}
{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}
<class 'dict'>

In [24]:
data["userId"]

1

In [25]:
formatted_json = json.dumps(data, indent=4)
print(formatted_json)

{
    "userId": 1,
    "id": 1,
    "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}

In [27]:
url = "https://jsonplaceholder.typicode.com/posts"
response = requests.get(url)
posts = response.json()
print(type(posts))
print(len(posts))
# Loop through JSON list
for post in posts[:5]:
    print(post["id"])
    print(post["title"])

<class 'list'>
100
1
sunt aut facere repellat provident occaecati excepturi optio reprehenderit
2
qui est esse
3
ea molestias quasi exercitationem repellat qui ipsa sit aut
4
eum et est occaecati
5
nesciunt quas odio

In [29]:
# Send query parameters
params = {
"userId": 1}
response = requests.get(
"https://jsonplaceholder.typicode.com/posts",
params=params
)
print(response.url)
filtered_posts = response.json()
print(filtered_posts)

https://jsonplaceholder.typicode.com/posts?userId=1
[{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}, {'userId': 1, 'id': 2, 'title': 'qui est esse', 'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'}, {'userId': 1, 'id': 3, 'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut', 'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'}, {'userId': 1, 'id': 4, 'title': 'eum et est occaecati', 'body': 'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit'}, {'userId': 1, 'id': 5, 'title': 'nesciunt quas odio', 'body': 'repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque'}, {'userId': 1, 'id': 6, 'title': 'dolorem eum magni eos aperiam quia', 'body': 'ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae'}, {'userId': 1, 'id': 7, 'title': 'magnam facilis autem', 'body': 'dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas'}, {'userId': 1, 'id': 8, 'title': 'dolorem dolore est ipsam', 'body': 'dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae'}, {'userId': 1, 'id': 9, 'title': 'nesciunt iure omnis dolorem tempora et accusantium', 'body': 'consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas'}, {'userId': 1, 'id': 10, 'title': 'optio molestias id quia eum', 'body': 'quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error'}]

In [30]:
headers = {
"User-Agent": "Mozilla/5.0",
"Accept": "application/json"
}
response = requests.get(
"https://jsonplaceholder.typicode.com/posts/1",
headers=headers
)
print(response.status_code)

200

In [31]:
#send post
new_post = {
"title": "Learning Requests",
"body": "This is tutorial content",
"userId": 1
}
response = requests.post(
"https://jsonplaceholder.typicode.com/posts",
json=new_post
)
print(response.status_code)
print(response.json())

201
{'title': 'Learning Requests', 'body': 'This is tutorial content', 'userId': 1, 'id': 101}

In [33]:
# Send PUT request
updated_post = {
"id": 1,
"title": "Updated Title",
"body": "Updated body",
"userId": 1
}
response = requests.put(
"https://jsonplaceholder.typicode.com/posts/1",
json=updated_post
)
print(response.json())
# Send PATCH request
patch_data = {
"title": "Patched Title"
}
response = requests.patch(
"https://jsonplaceholder.typicode.com/posts/1",
json=patch_data
)
print(response.json())

{'id': 1, 'title': 'Updated Title', 'body': 'Updated body', 'userId': 1}
{'userId': 1, 'id': 1, 'title': 'Patched Title', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

In [35]:
# Send DELETE request
response = requests.delete(
"https://jsonplaceholder.typicode.com/posts/1"
)
print(response.status_code)

200

In [36]:
# View response headers
response = requests.get(
"https://jsonplaceholder.typicode.com/posts/1"
)
print(response.headers)

{'Date': 'Tue, 26 May 2026 04:37:44 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'access-control-allow-credentials': 'true', 'Cache-Control': 'max-age=43200', 'etag': 'W/"124-yiKdLzqO5gfBrJFrcdJ8Yq0LGnU"', 'expires': '-1', 'nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'pragma': 'no-cache', 'report-to': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=cm0XxK3flZGYrw8w37tiomcHV5k7nozDTHOB%2BmX3LaQ%3D\\u0026sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d\\u0026ts=1752551786"}],"max_age":3600}', 'reporting-endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=cm0XxK3flZGYrw8w37tiomcHV5k7nozDTHOB%2BmX3LaQ%3D&sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d&ts=1752551786"', 'Server': 'cloudflare', 'vary': 'Origin, Accept-Encoding', 'via': '2.0 heroku-router', 'x-content-type-options': 'nosniff', 'x-powered-by': 'Express', 'x-ratelimit-limit': '1000', 'x-ratelimit-remaining': '999', 'x-ratelimit-reset': '1752551814', 'Age': '11871', 'cf-cache-status': 'HIT', 'Content-Encoding': 'zstd', 'CF-RAY': 'a01a16188de8002c-BOM', 'alt-svc': 'h3=":443"; ma=86400'}

In [37]:
print(response.headers["Content-Type"])
# Download image using binary content
image_url = "https://picsum.photos/200"
response = requests.get(image_url)
with open("random_image.jpg", "wb") as f:
    f.write(response.content)
print("Image downloaded")

application/json; charset=utf-8
Image downloaded

In [38]:
response = requests.get(
"https://jsonplaceholder.typicode.com/posts/1"
)
data = response.json()
with open("post.json", "w") as f:
    json.dump(data, f, indent=4)
print("JSON file saved")

JSON file saved

In [39]:
with open("post.json", "r") as f:
    loaded_data = json.load(f)
print(loaded_data)
# Convert API response to DataFrame
response = requests.get(
"https://jsonplaceholder.typicode.com/posts"
)
posts = response.json()
df = pd.DataFrame(posts)
print(df.head())
# Loop through API data
for post in posts[:5]:
    print("ID:", post["id"])
    print("TITLE:", post["title"])
    print("BODY:", post["body"])
    print("=" * 50)

{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}
   userId  id                                              title  \
0       1   1  sunt aut facere repellat provident occaecati e...
1       1   2                                       qui est esse
2       1   3  ea molestias quasi exercitationem repellat qui...
3       1   4                               eum et est occaecati
4       1   5                                 nesciunt quas odio

                                                body
0  quia et suscipit\nsuscipit recusandae consequu...
1  est rerum tempore vitae\nsequi sint nihil repr...
2  et iusto sed quo iure\nvoluptatem occaecati om...
3  ullam et saepe reiciendis voluptatem adipisci\...
4  repudiandae veniam quaerat sunt sed\nalias aut...
ID: 1
TITLE: sunt aut facere repellat provident occaecati excepturi optio reprehenderit
BODY: quia et suscipit
suscipit recusandae consequuntur expedita et cum
reprehenderit molestiae ut ut quas totam
nostrum rerum est autem sunt rem eveniet architecto
==================================================
ID: 2
TITLE: qui est esse
BODY: est rerum tempore vitae
sequi sint nihil reprehenderit dolor beatae ea dolores neque
fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis
qui aperiam non debitis possimus qui neque nisi nulla
==================================================
ID: 3
TITLE: ea molestias quasi exercitationem repellat qui ipsa sit aut
BODY: et iusto sed quo iure
voluptatem occaecati omnis eligendi aut ad
voluptatem doloribus vel accusantium quis pariatur
molestiae porro eius odio et labore et velit aut
==================================================
ID: 4
TITLE: eum et est occaecati
BODY: ullam et saepe reiciendis voluptatem adipisci
sit amet autem assumenda provident rerum culpa
quis hic commodi nesciunt rem tenetur doloremque ipsam iure
quis sunt voluptatem rerum illo velit
==================================================
ID: 5
TITLE: nesciunt quas odio
BODY: repudiandae veniam quaerat sunt sed
alias aut fugiat sit autem sed est
voluptatem omnis possimus esse voluptatibus quis
est aut tenetur dolor neque
==================================================

In [40]:
# Get nested JSON response
response = requests.get(
"https://jsonplaceholder.typicode.com/users/1"
)
user = response.json()
print(user)
# Access nested JSON values
print(user["name"])
print(user["email"])
print(user["address"]["city"])
print(user["company"]["name"])
# Convert JSON string into Python object
json_string = '''
{
"name": "Alice",
"age": 25
}
'''
python_data = json.loads(json_string)
print(python_data)
print(type(python_data))
# Convert Python object into JSON string
person = {
"name": "Bob",
"age": 30
}
json_output = json.dumps(person, indent=4)
print(json_output)
# Show common HTTP status codes
print("200 = OK")
print("201 = Created")
print("400 = Bad Request")
print("401 = Unauthorized")
print("403 = Forbidden")
print("404 = Not Found")
print("500 = Server Error")

{'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': {'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}, 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}
Leanne Graham
Sincere@april.biz
Gwenborough
Romaguera-Crona
{'name': 'Alice', 'age': 25}
<class 'dict'>
{
    "name": "Bob",
    "age": 30
}
200 = OK
201 = Created
400 = Bad Request
401 = Unauthorized
403 = Forbidden
404 = Not Found
500 = Server Error

In [41]:
# 3. Tokens (Authorization)
import requests
url = "https://jsonplaceholder.typicode.com/posts"
token = "my_secret_token"
headers = {
"Authorization": f"Bearer {token}"  # verify identity and access protected APIs.
    #provide secure communication
}
response = requests.get(url, headers=headers)
print(response.status_code)

200

In [43]:
# Pagination
import requests
url = "https://jsonplaceholder.typicode.com/posts"
params = {
"_page": 1, # no of page
"_limit": 5 # no of post per page
}
response = requests.get(url, params=params)
data = response.json()
print("Posts on page 1")
for post in data:
    print(post["id"], post["title"])

Posts on page 1
1 sunt aut facere repellat provident occaecati excepturi optio reprehenderit
2 qui est esse
3 ea molestias quasi exercitationem repellat qui ipsa sit aut
4 eum et est occaecati
5 nesciunt quas odio

In [44]:
## Multiple pages
import requests
base_url = "https://jsonplaceholder.typicode.com/posts"
page = 1
while page <= 3:
    params = {
    "_page": page,
    "_limit": 5
    }
    response = requests.get(base_url, params=params)
    posts = response.json()
    print(f"\nPage {page}")
    for post in posts:
        print(post["id"], post["title"])
    page += 1

Page 1
1 sunt aut facere repellat provident occaecati excepturi optio reprehenderit
2 qui est esse
3 ea molestias quasi exercitationem repellat qui ipsa sit aut
4 eum et est occaecati
5 nesciunt quas odio

Page 2
6 dolorem eum magni eos aperiam quia
7 magnam facilis autem
8 dolorem dolore est ipsam
9 nesciunt iure omnis dolorem tempora et accusantium
10 optio molestias id quia eum

Page 3
11 et ea vero quia laudantium autem
12 in quibusdam tempore odit est dolorem
13 dolorum ut in voluptas mollitia et saepe quo animi
14 voluptatem eligendi optio
15 eveniet quod temporibus